# Generated by Django 4.1.7 on 2023-03-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RabbitHole', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='RabbitHole.reply'),
        ),
        migrations.AddField(
            model_name='post',
            name='countlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='countlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='RabbitHole.post'),
        ),
    ]
