# Generated by Django 4.1.7 on 2023-03-08 10:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="default_avatars/default.png",
                upload_to=authentication.models.user_avatar_path,
            ),
        ),
    ]
